# Exercise 2.A Fundamentals of pandas

In [2]:
import numpy as np
import pandas as pd

## Series

In [3]:
# Plain Python objects

aa = [1, 2, 3, 4]

ab = (5, 6, 7, 8)

ac = {9, 10, 11, 12}

ad = {
    'first': 13,
    'second': 14,
    'third': 15,
    'fourth': 16
}

In [4]:
# Create Series objects

ser1 = pd.Series(aa)

ser2 = pd.Series(ab)

ser3 = pd.Series(list(ac))

ser4 = pd.Series(ad)

print(ser1)
print()
print(ser2)
print()
print(ser3)
print()
print(ser4)

0    1
1    2
2    3
3    4
dtype: int64

0    5
1    6
2    7
3    8
dtype: int64

0     9
1    10
2    11
3    12
dtype: int64

first     13
second    14
third     15
fourth    16
dtype: int64

In [10]:
# Attempt to create ser5 incorrectly

ser5 = pd.Series(17, 18, 19, 20)

# TypeError:
# Series.__init__() takes from 1 to 4 positional arguments but 5 were given

TypeError: Index(...) must be called with a collection of some kind, 18 was passed

## DataFrames from Series

In [12]:
# Create DataFrame from ser1

df1 = pd.DataFrame(ser1)

df1

   0
0  1
1  2
2  3
3  4

In [13]:
# Add new columns using insert()

df1.insert(1, "Column2", ser2)

df1.insert(2, "Column3", ser3)

df1

   0  Column2  Column3
0  1        5        9
1  2        6       10
2  3        7       11
3  4        8       12

In [14]:
# Add third column using ser4

df1.insert(3, "Column4", ser4)

df1

# ser4 uses dictionary keys as labels/indexes instead of numeric indexes.
# Because the indexes do not match df1's indexes, pandas fills the rows with NaN values.

   0  Column2  Column3  Column4
0  1        5        9      NaN
1  2        6       10      NaN
2  3        7       11      NaN
3  4        8       12      NaN

In [15]:
# Add a new row using loc

df1.loc[4] = [5, 9, 12, 0]

df1

   0  Column2  Column3  Column4
0  1        5        9      NaN
1  2        6       10      NaN
2  3        7       11      NaN
3  4        8       12      NaN
4  5        9       12      0.0

## Reading Data into a DataFrame

In [16]:
# Read sakila_example.csv

df2 = pd.read_csv("sakila_example.csv")

df2

FileNotFoundError: [Errno 2] No such file or directory: 'sakila_example.csv'